### ISSUE TITLE
集控请求时存在缓存

### ISSUE THREAD

**Issue by MKStoler4096** [ProjectCampus-CH/exam-showboard-next#39]
集控请求时存在缓存

**Comment by wjj-8283** [comment]
有一个思路就是点击返回主页或x或按下alt+f4时删除C:\Users\(用户名)\AppData\Roaming\examshowboard下所有带cache字样的文件夹，删除以后不影响“直接进入看板”功能

**Comment by MKStoler4096** [comment]
请求时禁用缓存就好了，没那么麻烦（）

**Comment by wjj-8283** [comment]
我用源码（最新的）编译测试了一下，没有问题了，唯一值得抱怨的是github的raw刷新太慢了，我更改都提交了3min了raw链接才刷新
