### ISSUE TITLE
（可选-设置）启动时自动加载配置文件

### ISSUE THREAD

**Issue by wjj-8283** [ProjectCampus-CH/exam-showboard-next#50]
### 背景与动机

有的时候我想要使用一些自动化的程序打开examshowboard，但是打开后还是免不了一些人工操作

### 想要实现或优化的功能

- [x] 实现每次打开看板都自动直接进入看板
- [ ] ~支持使用命令行参数调用配置文件（如在启动命令行参数中添加json位置或远程json或者直接进入看板）~

**Comment by MKStoler4096** [comment]
第一个吧，实在想不出来electron框架怎么获取启动参数（）~简称实力不行~

**Comment by wjj-8283** [comment]
我认为最舒服的是能通过设置定义每一次启动时的加载源（上一次的配置、指定文件、远程url……），这样也是一种”自动化’（更改全部集中到一个文件上）

**Comment by MKStoler4096** [comment]
所以在开发设置了（）
但是我`vue`，`ts`，`js`都是一个暑假~水~学出来的（简称啥也不会），预计开发速度会很慢。
*（其实我以前是主攻vb6和php的）*

**Comment by wjj-8283** [comment]
像我这种要到高考结束后才能学习编程的人好很多了（到现在都只会写一些python脚本，其它语言代码全靠字面意思看懂）

**Comment by MKStoler4096** [comment]
基本完成了
