### ISSUE TITLE
当前科目和时钟总是有0.5~1s的时间差

### ISSUE THREAD

**Issue by wjj-8283** [ProjectCampus-CH/exam-showboard-next#59]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ProjectCampus-CH/dsz-exam-showboard-next?include_prereleases&style=flat) ，并看过[最新提交](https://github.com/ProjectCampus-CH/dsz-exam-showboard-next/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ProjectCampus-CH/dsz-exam-showboard-next/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

两个时间同步

### 实际结果

有时间差

### 重现步骤

打开有考试的看板

### 应用版本

最新master分支编译的

### 操作系统版本

10.0.26100.2454，Windows 11 IoT企业版LTSC

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by MKStoler4096** [comment]
已知，但是没办法，这两个组件是独立的，不能用同一个刷新

**Comment by MKStoler4096** [comment]
@hello8693DSZ 来帮我想个办法呗
