### ISSUE TITLE
Linux 下无法打开，构建不正常

### ISSUE THREAD

**Issue by MKStoler4096** [ProjectCampus-CH/exam-showboard-next#99]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ProjectCampus-CH/dsz-exam-showboard-next?include_prereleases&style=flat) ，并看过[最新提交](https://github.com/ProjectCampus-CH/dsz-exam-showboard-next/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ProjectCampus-CH/dsz-exam-showboard-next/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

当然是能打开^_^

### 实际结果

打不开（白屏）X_X

### 重现步骤

UOS 下无法打开，构建不正常

### 堆栈跟踪（可选）

```shell
没有
```

### 应用版本

1.2.5

### 操作系统版本

5.10.0-amd64-desktop（家庭版（22.0））

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by hello8693DSZ** [comment]
这个可能是uos的问题。我在本地测试ubuntu以及我的开发环境macOS都是没问题的

**Comment by thefirsttime2021** [comment]
Windows也一样，打不开（白屏），构建就是出错了。

**Comment by MKStoler4096** [comment]
> Windows也一样，打不开（白屏），构建就是出错了。


看一下这个[行不行](https://github.com/ProjectCampus-CH/exam-showboard-next/actions/runs/12481351893)？ @thefirsttime2021

**Comment by MKStoler4096** [comment]
我这里 Windows 正常，Linux 照样 Build 不出来（

**Comment by MKStoler4096** [comment]
好了，从appimage里面解压出来能在arch上运行
